apiVersion: batch/v1
kind: Job
metadata:
  name: plgm
  namespace: lab
spec:
  template:
    spec:
      containers:
      - name: plgm
        image: plgm:latest
        imagePullPolicy: Never  # <--- used for local Docker Desktop images
        command: ["./plgm", "config.yaml"]
        env:
        # Override the URI in config.yaml with the internal K8s DNS
        # This talks directly to the pod
        - name: PLGM_URI
          value: "mongodb://test-rs-0.test-rs.lab.svc.cluster.local:27017,test-rs-1.test-rs.lab.svc.cluster.local:27017,test-rs-2.test-rs.lab.svc.cluster.local:27017/?authSource=admin"
        - name: PLGM_USERNAME
          value: "root"
        - name: PLGM_PASSWORD
          value: "percona"
        - name: PLGM_REPLICA_SET
          value: "rs"
        - name: PLGM_READ_PREFERENCE
          value: "nearest"  
        - name: PLGM_CONCURRENCY
          value: "40"
        - name: PLGM_DIRECT_CONNECTION
          value: "false"  
      restartPolicy: Never
  backoffLimit: 0

